# Generated by Django 3.2.8 on 2021-11-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youTube_app', '0004_alter_downloaduser_user_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloaduser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='downloaduser',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
